---

- hosts: localhost
  connection: local
  tasks:
    - name: create json body for create data source grafana
      template:
        src=./group_vars/create_data_source.json
        dest=/var/tmp/create_data_source_{{item}}.json
      with_items: server_ip.split(',')

    - name: Create data source grafana
      uri:
        url=http://{{grafana_server}}:{{grafana_port}}/api/datasources
        method=POST
        HEADER_Content-Type="application/json"
        user='{{grafana_user}}'
        password='{{grafana_passwd}}'
        force_basic_auth=yes
        body='{{ lookup("file", '/var/tmp/create_data_source_' + item +'.json') }}'
        body_format=json
        status_code=200,201,204
      with_items: server_ip.split(',')

    - name: create json body for create dashboard
      template:
        src=./group_vars/docker_dashboard.json
        dest=/var/tmp/create_dashboard_{{item}}.json
      with_items: server_ip.split(',')

    - name: Create dashboard
      uri:
        url=http://{{grafana_server}}:{{grafana_port}}/api/dashboards/db
        method=POST
        HEADER_Content-Type="application/json"
        user='{{grafana_user}}'
        password='{{grafana_passwd}}'
        force_basic_auth=yes
        body='{{ lookup("file", '/var/tmp/create_dashboard_'+ item +'.json') }}'
        body_format=json
        status_code=200,201,204
      with_items: server_ip.split(',')